<li class="wide">
    <div class="field">
        <label class="required" for="billing:is_business_address"><em>*</em><?php echo $this->__('Is Business Address') ?></label>

        <div class="input-box">
            <select class="required-entry" id="billing:is_business_address" name="billing[is_business_address]" title="<?php echo $this->__('Is Business Address') ?>">
                <option value="0">
                    <?php print $this->__('No') ?>
                </option>

                <option value="1">
                    <?php print $this->__('Yes') ?>
                </option>
            </select>
        </div>
    </div>
</li>
<li class="wide">
    <div class="field" id="field-billing-tax_code">
        <label class="required" for="billing:tax_code"><em>*</em><?php echo $this->__('Tax Code') ?></label>

        <div class="input-box">
            <input class="input-text required-entry validate-tax_code" id="billing:tax_code" name="billing[tax_code]" style="text-transform:uppercase;" title="<?php echo $this->__('Tax Code') ?>" type="text" value="<?php echo $this->htmlEscape($this->getAddress()->getTaxCode()) ?>">
        </div>
    </div>
</li>

<li class="fields">
    <div class="field" id="field-billing-company">
        <label class="required" for="billing:company"><em>*</em><?php echo $this->__('Company') ?></label>

        <div class="input-box">
            <input class="input-text required-entry" id="billing:company" name="billing[company]" title="<?php echo $this->__('Company') ?>" type="text" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>">
        </div>
    </div>

    <div class="field" id="field-billing-vat_number">
        <label class="required" for="billing:vat_number"><em>*</em><?php echo $this->__('VAT Number') ?></label>

        <div class="input-box">
            <input class="input-text required-entry validate-vat_number" id="billing:vat_number" name="billing[vat_number]" title="<?php echo $this->__('VAT Number') ?>" type="text" value="<?php echo $this->htmlEscape($this->getAddress()->getVatNumber()) ?>">
        </div>
    </div>
</li>

<?php
    $block = new Webgriffe_TaxIdPro_Block_AddressEdit();
?>
<script type="text/javascript">
//<![CDATA[
// Billing.prototype.newAddress = function(isNew) {
//     if (isNew) {
//         this.resetSelectedAddress();
//         Element.show('billing-new-address-form');
//         billig_special_taxid_pro_event();
//     } else {
//         Element.hide('billing-new-address-form');
//     }
// };
if (parseInt($('billing:is_business_address').getValue())) { // If is a business address...
    //$('field-billing-tax_code').hide();
    //$('billing:tax_code').setValue('');
    $('field-billing-vat_number').show();
    $('field-billing-company').show();
} else {
    //$('field-billing-tax_code').show();
    $('field-billing-vat_number').hide();
    $('billing:vat_number').setValue('');
    $('field-billing-company').hide();
    $('billing:company').setValue('');
}
billig_special_taxid_pro_event = function() {
    $('billing:is_business_address').observe('change', function(event) {
        if (parseInt(this.getValue())) { // If is a business address...
            //$('field-billing-tax_code').hide();
            //$('billing:tax_code').setValue('');
            $('field-billing-vat_number').show();
            $('field-billing-company').show();
        } else {
            //$('field-billing-tax_code').show();
            $('field-billing-vat_number').hide();
            $('billing:vat_number').setValue('');
            $('field-billing-company').hide();
            $('billing:company').setValue('');
        }
    });
    $('billing:tax_code').observe('blur', function(event) {
        this.setValue(this.getValue().toUpperCase());
    });
    $('billing:vat_number').observe('blur', function(event) {
        this.setValue(this.getValue().toUpperCase());
    });
    Validation.addAllThese([
        ['validate-tax_code', '<?php echo $this->__("Please, enter a valid Tax Code.") ?>',
            function(v, elm) {
                elm.value = elm.value.toUpperCase();
                v = elm.value; <?php echo $block->getFormatsJs('tax_code'); ?>
                var ccode = $('billing:country_id').value;
                if (isValid[ccode] == undefined) {
                    isValid[ccode] = true;
                }
                return Validation.get('IsEmpty').test(v) || isValid[ccode];
            }
        ],
        ['validate-vat_number', '<?php echo $this->__("Please, enter a valid VAT Number.") ?>',
            function(v, elm) {
                elm.value = elm.value.toUpperCase();
                v = elm.value; <?php echo $block->getFormatsJs('vat_number'); ?>
                var ccode = $('billing:country_id').value;
                if (isValid[ccode] == undefined) {
                    isValid[ccode] = true;
                }
                return Validation.get('IsEmpty').test(v) || isValid[ccode];
            }
        ]
    ]);
}
Event.observe(window, 'load', billig_special_taxid_pro_event);
Event.observe(window, 'load', function() {
    billingCountryIsRequired($('billing:country_id'));
    $('billing:country_id').onchange = function() {
        billingCountryIsRequired($('billing:country_id'));
    }
});

function billingCountryIsRequired(element) {
    var taxcodeCountries = '<?php echo $block->getCountriesJs("tax_code") ?>';
    if (taxcodeCountries.indexOf(element.getValue()) >= 0) {
        $$('#field-billing-tax_code label em')[0].innerHTML = '*';
        $('billing:tax_code').className = 'required-entry input-text validate-tax_code';
    } else {
        $$('#field-billing-tax_code label em')[0].innerHTML = '';
        $('billing:tax_code').className = 'input-text validate-tax_code';
    }
    var vatnumberCountries = '<?php echo $block->getCountriesJs("vat_number") ?>';
    if (vatnumberCountries.indexOf(element.getValue()) >= 0) {
        $$('#field-billing-vat_number label em')[0].innerHTML = '*';
        $('billing:vat_number').className = 'required-entry input-text validate-vat_number';
    } else {
        $$('#field-billing-vat_number label em')[0].innerHTML = '';
        $('billing:vat_number').className = 'input-text validate-vat_number';
    }
}
//]]>
</script>
