<?php
header("content-Type: text/html; charset=Utf-8");

$suID = 'jy1215jy@gmail.com';
$processID = '50000016';
$stCate = '';
$stCode = '';
$rtURL = Mage::getBaseUrl().'firecheckout/';
$webPara = '';
if($_POST['processID']){
 $processID = $_POST['processID'];
 $stCate = $_POST['stCate'];
 $stCode = $_POST['stCode'];
 $stName = $_POST['stName'];
 $stAddr = $_POST['stAddr'];
 $stTel = $_POST['stTel'];
 $webPara = $_POST['webPara'];
}
?>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li class="wide">
<!--                            <label for="ordercomment-comment">--><?php //echo Mage::helper('ordercomment')->__('Order Comment') ?><!--</label>-->
                            <button style="margin-bottom: 10px;" id='get_map' type="button" title="超商地圖" class="button" onclick="show_map();">查看超商代碼</button>
                            <div class="input-box">
                                <textarea id="ordercomment-comment" class="input-text validation-passed" name="ordercomment[comment]" title="<?php echo $this->__('Order Comment') ?>" rows="5" cols="10"><?php if($_POST['processID']): ?><?php echo "超商店名: ".$stName."\n";echo "超商代號: ".$stCate.$stCode."\n";echo "超商地址: ".$stAddr."\n";?><?php endif;?></textarea>
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>

    <?php if ($this->getAgreements()): ?>
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
            <li>
                <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                    <?php if ($_a->getIsHtml()):?>
                    <?php echo $_a->getContent() ?>
                    <?php else:?>
                    <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                    <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                </p>
            </li>
            <?php endforeach ?>
        </ol>
    <?php endif; ?>
</form>

<script type="text/javascript">
    jQuery('#get_map').on('click',function(){
        suID = "<?php echo $suID?>";
        processID = "<?php echo $processID?>";
        stCate = "<?php echo $stCate?>";
        stCode = "<?php echo $stCode?>";
        rtURL = "<?php echo $rtURL?>";
        webPara = "<?php echo $webPara?>";

        mapUrl = "http://map.ezship.com.tw/ezship_map_web.jsp?suID=" + suID +
            "&processID="+ processID + "&stCate=" + stCate + "&stCode="+stCode + "&rtURL="+rtURL +"&webPara="+webPara;

        window.location = mapUrl;
    })

</script>