<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
<?php if ($this->getOrderId()):?>
    <?php if ($this->getCanViewOrder()) :?>
        <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
    <?php  else :?>
        <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
    <?php endif;?>

    <p style="margin-top: 5px;"><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>

    <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
        <p style="margin-top: 5px;">
            <?php echo $this->__('列印定單明細 <a href="%s" style="text-decoration: underline;" onclick="this.target=\'_blank\'">按此列印</a>', $this->getPrintUrl()) ?>
        </p>
    <?php endif;?>

    <div class="amt-info" style="margin-top: 5px; display: none;">
        <p>*** 請於匯款完成後簡訊 (0975290922) 或是 LINE (nawonda) 回傳銀行帳號後四碼 ***</p>
        <div style="width: 200px; background-color: #f5f5f5; padding: 10px; margin-top: 10px;">
            <p style="margin-top: 5px;">銀行轉帳/ATM轉帳</p>
            <p style="margin-top: 5px;">戶名：張維宇</p>
            <p style="margin-top: 5px;">銀行代碼與名稱：031-國泰世華</p>
            <p style="margin-top: 5px;">分行名稱：仁愛分行</p>
            <p style="margin-top: 5px;">帳號：201506013432</p>
        </div>

    </div>
<?php endif;?>

<?php
if ($blockId = Mage::getStoreConfig('checkoutsuccess/general/block_top')) :
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
endif;
?>
<div class="clearer"></div>

<?php
if (Mage::getStoreConfigFlag('checkoutsuccess/general/detailed_info')
    && Mage::registry('current_order')) :

    echo $this->getChildHtml();
endif;
?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<?php
if ($blockId = Mage::getStoreConfig('checkoutsuccess/general/block_bottom')) :
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
endif;
?>
<div class="clearer"></div>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>

<script type="text/javascript">

    if(jQuery('.pay-atm')){
        jQuery('.amt-info').show();
    }
</script>